### ISSUE TITLE
Testcase for TLS client authentication would be cool

### ISSUE THREAD

**Issue by ulrj** [chromium/badssl.com#317] opened 2017-10-12 15:06 UTC
If you offered test-client certificates (valid and invalid) and an endpoint that demands TLS client authentication would be cool.

**Comment by april** [comment] 2017-10-12 20:05
I don't blame you for missing this, but it's actually a duplicate of #27. The good news is that it's a project I am actively working on.  :)

**Closed by april** 2017-10-12 20:05 UTC
