### ISSUE TITLE
TLS check is only connecting via 1.2

### ISSUE THREAD

**Issue by apolloniusoftyana** [chromium/badssl.com#370] opened 2018-10-11 20:30 UTC
![screen shot 2018-10-11 at 1 29 28 pm](https://user-images.githubusercontent.com/44034039/46831978-be1aa200-cd59-11e8-8b37-b41de81ac4c1.png)
![screen shot 2018-10-11 at 1 29 19 pm](https://user-images.githubusercontent.com/44034039/46831979-be1aa200-cd59-11e8-8d74-d075a03ca3ec.png)
![screen shot 2018-10-11 at 1 29 08 pm](https://user-images.githubusercontent.com/44034039/46831980-be1aa200-cd59-11e8-86fa-f3a00f8e7896.png)

**Comment by christhompson** [comment] 2019-06-07 21:23
I can't reproduce this anymore (both tls-v1-0 and tls-v1-1 subdomains are showing TLS 1.0 and 1.1 respectively in dev tools for me), so closing. If you're still running into this feel free to re-open and add more details.

**Closed by christhompson** 2019-06-07 21:23 UTC
